export default {
    STARTP: 'STARTP',
    ENDP: 'ENDP',
    WALL: 'WALL',
    GENERATE: 'GENERATE',
    PATHFIND: 'PATHFIND',
    RESET: 'RESET',
    STEP: 'STEP',
    GENERATE_FOG: 'GENERATE_FOG',
    STEP_FOG: 'STEP_FOG',
}